server:
  port: 9998
spring:
  application:
    name: azblog-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8201/eureka #注册中心地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向服务中心注册自定义id
    lease-renewal-interval-in-seconds: 50 #每次发送心跳的时间
turbine:
  #要监控的微服务serviceId,多个用逗号隔开
  app-config: azblog-article,azblog-search
  clusterNameExpression: "'default'"

